quarkus:
  http:
    port: 8091
    cors: true
  swagger-ui:
    always-include: true

kafka:
  bootstrap-servers: "46.101.136.244:9092"
  poll-records: 100
  auto-commit: true
  offset-reset: "earliest"
  group-name: "greeneagle"



"%dev":
  quarkus:
    swagger-ui:
      always-include: true

"%test":
