#Server Config
server:
  port: 8080

#App at.kara.greeneagle
app:
  production: false

spring:
  kafka:
    consumer:
      bootstrap-servers: 46.101.136.244:9092
      group-id: greeneagle
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer