quarkus:
  http:
    port: 8091
    cors: true

kafka:
  bootstrap-servers: "46.101.136.244:9092"
  poll-records: 100
  auto-commit: false
  offset-reset: "latest"

  prefix:
    zone: "zone"
    vehicle-data: "vehicle-data"

"%dev":

"%test":
