quarkus:
  http:
    port: 8091
    cors: true
  swagger-ui:
    always-include: true

kafka:
  bootstrap-servers: "136.243.131.9:9092"
  poll-records: 100
  auto-commit: true
  offset-reset: "earliest"
  group-name: "greeneagle"



"%dev":
  kafka:
    bootstrap-servers: "193.26.156.80:9092"

  quarkus:
    swagger-ui:
      always-include: true

"%test":
